# Generated by Django 3.2.14 on 2023-03-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParlourApp', '0011_service_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_status',
        ),
    ]
