# Generated by Django 4.1.7 on 2023-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParlourApp', '0013_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Approved', 'Approved')], default='Approved', max_length=150),
        ),
    ]
