# Generated by Django 4.1.7 on 2023-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0007_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.TextField(blank=True),
        ),
    ]
