# Generated by Django 4.1.7 on 2023-04-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0008_product_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
    ]
