# Generated by Django 4.1.7 on 2023-04-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0009_remove_product_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade1', models.TextField(blank=True)),
                ('shade2', models.TextField(blank=True)),
                ('shade3', models.TextField(blank=True)),
                ('shade4', models.TextField(blank=True)),
                ('shade5', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.product')),
            ],
        ),
    ]
