# Generated by Django 4.1.7 on 2023-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0010_shades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shades',
            name='shade1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shades',
            name='shade2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shades',
            name='shade3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shades',
            name='shade4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shades',
            name='shade5',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
