# Generated by Django 4.1.7 on 2023-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
