# Generated by Django 4.1.7 on 2023-04-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
