# Generated by Django 4.1.7 on 2023-04-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='razorpay_payment_signature',
        ),
    ]
