# Generated by Django 4.1.7 on 2023-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cart_options_remove_cartitem_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
