# Generated by Django 4.1.7 on 2023-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cartitem_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Out for shipping', 'Out for shipping'), ('On the way', 'On the way'), ('Completed', 'Completed')], default='Order Confirmed', max_length=150),
        ),
    ]
