# Generated by Django 4.1.7 on 2023-04-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_order_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
