# Generated by Django 4.1.7 on 2023-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_order_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
